import {
  Landmark,
  GitBranch,
  Plus,
  BarChart3,
  ArrowLeft,
  ArrowRight,
  FileText,
  ClipboardList,
  ClipboardCheck,
  Paperclip,
  DollarSign,
  Sparkles,
  Wand2,
  RefreshCw,
  BadgeCheck,
  BarChart2,
  FlaskConical,
  Ban,
  Wrench,
  Building2,
  Calculator,
  Calendar,
  CalendarRange,
  History,
  Check,
  CheckCircle2,
  ListChecks,
  ChevronLeft,
  ChevronRight,
  Brush,
  X,
  CloudOff,
  CloudDownload,
  Copy,
  Trash2,
  Trash,
  ListX,
  FileText as DescriptionIcon,
  PieChart,
  Pencil,
  FileEdit,
  Trophy,
  AlertCircle,
  AlertTriangle,
  CalendarDays,
  CalendarCheck,
  ChevronDown,
  Heart,
  Download,
  Search,
  FolderX,
  FolderOpen,
  FolderSync,
  MessageSquare,
  Gavel,
  LayoutGrid,
  Users,
  ShieldCheck,
  Clock,
  Info,
  LineChart,
  Star,
  MapPin,
  Lock,
  LogOut,
  Cpu,
  MoreVertical,
  StickyNote,
  Bell,
  ExternalLink,
  CreditCard,
  Loader2,
  FileImage,
  Play,
  Shield,
  Printer,
  AlertOctagon,
  Brain,
  ScrollText,
  Mic,
  Save,
  Beaker,
  SearchX,
  ShieldAlert,
  Send,
  Settings,
  Bot,
  Code2,
  Square,
  Lightbulb,
  Zap,
  Globe,
  TrendingDown,
  TrendingUp,
  Upload,
  UploadCloud,
  BadgeCheck as VerifiedIcon,
  KeyRound,
  Link,
  List,
  Receipt,
  type LucideIcon,
} from "lucide-react";

/**
 * Material Icons Outlined → Lucide React mapping
 * Used by the Icon bridge component for gradual migration
 */
export const iconMap: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_tree: GitBranch,
  add: Plus,
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: FileText,
  assessment: ClipboardList,
  assignment: ClipboardList,
  assignment_turned_in: ClipboardCheck,
  attach_file: Paperclip,
  attach_money: DollarSign,
  auto_awesome: Sparkles,
  auto_fix_high: Wand2,
  autorenew: RefreshCw,
  badge: BadgeCheck,
  bar_chart: BarChart2,
  biotech: FlaskConical,
  block: Ban,
  build: Wrench,
  business: Building2,
  calculate: Calculator,
  calendar_today: Calendar,
  calendar_view_week: CalendarRange,
  change_history: History,
  check: Check,
  check_circle: CheckCircle2,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  cleaning_services: Brush,
  close: X,
  cloud_done: CloudOff,
  cloud_download: CloudDownload,
  content_copy: Copy,
  delete: Trash2,
  delete_outline: Trash,
  delete_sweep: ListX,
  description: DescriptionIcon,
  donut_large: PieChart,
  edit: Pencil,
  edit_note: FileEdit,
  emoji_events: Trophy,
  error: AlertCircle,
  error_outline: AlertTriangle,
  event: CalendarDays,
  event_available: CalendarCheck,
  expand_more: ChevronDown,
  favorite: Heart,
  file_download: Download,
  find_in_page: Search,
  folder_off: FolderX,
  folder_open: FolderOpen,
  folder_shared: FolderSync,
  forum: MessageSquare,
  gavel: Gavel,
  grid_view: LayoutGrid,
  groups: Users,
  health_and_safety: ShieldCheck,
  history: Clock,
  info: Info,
  insights: LineChart,
  interests: Star,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  memory: Cpu,
  more_vert: MoreVertical,
  note_alt: StickyNote,
  notifications: Bell,
  open_in_new: ExternalLink,
  payments: CreditCard,
  pending: Loader2,
  picture_as_pdf: FileImage,
  play_arrow: Play,
  policy: Shield,
  print: Printer,
  priority_high: AlertOctagon,
  psychology: Brain,
  rate_review: ScrollText,
  receipt_long: Receipt,
  record_voice_over: Mic,
  refresh: RefreshCw,
  rule: ListChecks,
  save: Save,
  schedule: Clock,
  science: Beaker,
  search: Search,
  search_off: SearchX,
  security: ShieldAlert,
  send: Send,
  settings: Settings,
  smart_toy: Bot,
  source: Code2,
  star: Star,
  stop: Square,
  strategy: Lightbulb,
  summarize: FileText,
  sync: RefreshCw,
  task_alt: CheckCircle2,
  thumb_down: TrendingDown,
  thumb_up: TrendingUp,
  tips_and_updates: Zap,
  travel_explore: Globe,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  upload: Upload,
  upload_file: UploadCloud,
  verified: VerifiedIcon,
  vpn_key: KeyRound,
  warning: AlertTriangle,
};

export default iconMap;
